services:
  # Backend API Service
  - type: web
    name: iplt20-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Static Site
  - type: web
    name: iplt20-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://iplt20-backend.onrender.com 